{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "okg.fullname" . }}-runtime
  labels:
    {{- include "okg.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "okg.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: runtime
{{- end }}
